id: A9654E9B7
title: Extemporary Practice of Longevity for Oneself or Others
type: translation
pechas:
- I02718278
- ID1D4D122
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:09:10.970897
  last_modified_at: 2023-01-04 13:09:10.970901
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I02718278/18EB: 3B7E
  ID1D4D122/ECE3: 3B7E
